---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/users/{user_id}/posts/{post_id}/comments":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    - name: post_id
      in: path
      description: post_id
      required: true
      schema:
        type: string
    get:
      summary: list comments
      responses:
        '200':
          description: successful
    post:
      summary: create comment
      responses:
        '200':
          description: successful
  "/api/users/{user_id}/posts/{post_id}/comments/new":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    - name: post_id
      in: path
      description: post_id
      required: true
      schema:
        type: string
    get:
      summary: new comment
      responses:
        '200':
          description: successful
  "/api/users/{user_id}/posts/{post_id}/comments/{id}/edit":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    - name: post_id
      in: path
      description: post_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: edit comment
      responses:
        '200':
          description: successful
  "/api/users/{user_id}/posts/{post_id}/comments/{id}":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    - name: post_id
      in: path
      description: post_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show comment
      responses:
        '200':
          description: successful
    patch:
      summary: update comment
      responses:
        '200':
          description: successful
    put:
      summary: update comment
      responses:
        '200':
          description: successful
    delete:
      summary: delete comment
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
